# Default values for devops-playground umbrella chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Values for the backend subchart
backend:
  replicaCount: 1
  image:
    tag: "latest"
  service:
    port: 8000

# Values for the frontend subchart
frontend:
  replicaCount: 1
  image:
    tag: "latest"
  service:
    port: 80

# Values for the network subchart
network:
  enabled: true
  hosts:
    - paths:
        - path: /
          pathType: Prefix
          serviceName: frontend-service
          servicePort: 80